#################################################
# Miscellaneous sensors
#################################################

- platform: sql
  db_url: !secret mysql_url
  queries:
    - name: HASS DB Size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: MB
- platform: influxdb
  host: a0d7b954-influxdb
  port: 8086
  username: !secret influxdb_user
  password: !secret influxdb_pass
  queries:
      - name: InfluxDB Database Size
        unit_of_measurement: MB
        value_template: '{{ (value | float / 1024 /1024) | round(1) }}'
        group_function: sum
        measurement: '"monitor"."shard"'
        database: _internal
        where: 'time > now() - 10s'
        field: diskBytes
- platform: sauresha
  email: !secret saures_user
  password: !secret saures_pass
  flat_id: !secret saures_flat_id
  scan_interval:
    minutes: 90
  counters_sn: 
      - "13193152"
      - 09-104476
  controllers_sn: 
      - "1113513"
#- platform: plex
- platform: time_date
  display_options:
    - 'time'
    - 'date'
- platform: moon
- platform: version
  source: local
- platform: version
  source: hassio
- platform: uptime
  unit_of_measurement: hours
- platform: template
  sensors:
    entrance_door_status:
      value_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d00031c790f', "on") %}Открыта
        {% elif is_state('binary_sensor.door_window_sensor_158d00031c790f', "off") %}Закрыта
        {% else %}Unavailable
        {% endif %}
    local_pressure_mmhg:
      value_template: '{{ (((states.sensor.pressure_158d0003230618.state) | float) / 1.333) | round(2) }}'
      unit_of_measurement: mmHg
    boiler_status:
      friendly_name: "Electrolux Centurio IQ Status"
      value_template: >
        {% if (states('sensor.tplinksmartplug01_amps') | float) > 4 %}On{% else %}Off{% endif %}
#    mirobot_current_fan_speed:
#      value_template: >
#        {% if state_attr('vacuum.xiaomi_vacuum_cleaner', "fan_speed") == 101 %}Quiet
#        {% elif state_attr('vacuum.xiaomi_vacuum_cleaner', "fan_speed") == 102 %}Balanced
#        {% elif state_attr('vacuum.xiaomi_vacuum_cleaner', "fan_speed") == 103 %}Turbo
#        {% elif state_attr('vacuum.xiaomi_vacuum_cleaner', "fan_speed") == 104 %}Max
#        {% endif %}
    mirobot_current_fan_speed:
      value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'fan_speed') }}"
    xiaomi_gas_density:
      value_template: "{{ state_attr('binary_sensor.natgas_sensor_158d000413b210', 'Density') }}"
- platform: min_max
  name: Average Temperature In Flat
  type: median
  entity_ids:
    - sensor.temperature_158d0003931aec
    - sensor.temperature_158d0003230618
    - sensor.temperature_158d0003931b0e
    - sensor.temperature_158d00039e2ecb
    - sensor.a4c138414e9a_temperature
- platform: min_max
  name: Average Humidity In Flat
  type: median
  entity_ids:
    - sensor.humidity_158d0003931aec
    - sensor.humidity_158d0003230618
    - sensor.humidity_158d0003931b0e
    - sensor.humidity_158d00039e2ecb
    - sensor.a4c138414e9a_humidity