#################################################
# Gismeteo sensors
#################################################

- platform: gismeteo
  forecast: true
  monitored_conditions:
    - rain
    - snow
    - storm
    - geomagnetic
- platform: template
  sensors:
    gismeteo_temperature:
      unit_of_measurement: °C
      value_template: '{{ states.weather.gismeteo.attributes.temperature }}'
    gismeteo_pressure:
      unit_of_measurement: hPa
      value_template: '{{ states.weather.gismeteo.attributes.pressure }}'
    gismeteo_pressure_mmhg:
      unit_of_measurement: mmHg
      value_template: '{{ (state_attr("weather.gismeteo", "pressure") / 1.333) | round(2) }}'