#################################################
# Core config
#################################################

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 172.16.16.0/24
      trusted_users:
        172.16.16.0/24: 5eb99a825ace48779fad323aac28014d
  name: Home, Sweeet Home...
  time_zone: !secret home_timezone
  unit_system: metric
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/
    - /config/www/weather_icons/
    - /config/www/cam_snapshots/

#################################################
# Features
#################################################

config:
hassio:
system_health:
stream:
zeroconf:
ssdp:
sun:
map:
mobile_app:
wwlln:
wake_on_lan:
person:
logbook:
history:

http:
  base_url: !secret external_url
  use_x_forwarded_for: true
  trusted_proxies: 
    - 127.0.0.1
    - 172.16.16.253
  ip_ban_enabled: true
  login_attempts_threshold: 3

logger:
  default: warn
#  logs:
#    custom_components.sonoff: debug
#    homeassistant.components.tuya: debug
#    homeassistant.components.http.ban: warning
#    homeassistant.components.device_tracker: debug

system_log:
  max_entries: 50
  fire_event: true

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

recorder:
  db_url: !secret mysql_url
  purge_keep_days: 7
  exclude:
    domains:
      - updater
      - automation
      - script
      - camera
      - input_datetime
      - input_number
      - input_select
    entities:
      - sensor.time
      - sensor.date
      - sensor.uptime
      - sensor.moon
      - sun.sun
    event_types:
      - call_service

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pass
  max_retries: 5
  default_measurement: state
#  exclude:
#    domains:
#      - automation
#      - sun
  include:
    entities: !include influxdb_conf/influxdb_include_entities.yaml

lovelace:
  mode: yaml

tts:
  - platform: google_translate
    language: 'ru'

weather:
  - platform: gismeteo
    mode: daily

discovery:
  ignore:
    - yeelight
    - igd

auto_backup:
  auto_purge: true

xiaomi_aqara:
  discovery_retry: 30
  gateways:
    - mac: 04cf8ca0db1e
      host: 172.16.16.215
      key: !secret xiaomi_aqara_key

light:
  - platform: switch
    name: Детская - подсветка на окне
    entity_id: switch.plug_158d00033b702e

vacuum:
  - platform: xiaomi_miio
    host: 172.16.16.219
    token: !secret mi_vacuum_1s_token

fan:
  - platform: xiaomi_miio
    host: 172.16.16.224
    name: Smartmi Humidifier 01
    token: !secret xiaomi_air_humidifier_01_token

tuya:
  platform: smart_life
  username: !secret tuya_user
  password: !secret tuya_pass
  country_code: "7"

sonoff:
#  username: !secret sonoff_username
#  password: !secret sonoff_pass
  devices:
    1000b6831b:
      devicekey: 87c5267d-054f-4a71-8c51-49d027b80d71
      device_class: light

tplink:
  discovery: false
  switch:
    - host: 172.16.16.213
    - host: 172.16.16.216

transmission:
  host: 172.16.16.253

#zabbix:
#  host: home.intra
#  username: !secret zbx_user
#  password: !secret zbx_pass

telegram_bot:
  - platform: webhooks # or "polling"
    url: !secret tlg_webhook_proxy_url
    api_key: !secret telegram_bot_token
    trusted_networks:
      - !secret tlg_webhook_proxy_ip
    allowed_chat_ids:
      - !secret tlg_stall_id
      - !secret tlg_iborisochka_id

notify:
  - name: telegram_stall
    platform: telegram
    chat_id: !secret tlg_stall_id
  - name: telegram_iborisochka
    platform: telegram
    chat_id: !secret tlg_iborisochka_id

#################################################
# Inclusions
#################################################

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
camera: !include_dir_merge_list entities/cameras
counter: !include_dir_merge_named entities/counters
device_tracker: !include_dir_merge_list entities/device_trackers
sensor: !include_dir_merge_list entities/sensors
binary_sensor: !include_dir_merge_list entities/binary_sensors
switch: !include_dir_merge_list entities/switches
media_player: !include_dir_merge_list entities/media_players
input_select: !include_dir_merge_named entities/input_select
input_number: !include_dir_merge_named entities/input_number
input_datetime: !include_dir_merge_named entities/input_datetime
shell_command: !include_dir_merge_named entities/shell_commands/shcom_all.yaml
yeelight: !include entities/yeelight/yeelight.yaml