#################################################
# Sensors battery status
#################################################

- platform: template
  sensors:
    battery_status_158d0003230618:
      friendly_name: "Заряд батареи датчика температуры (Гостинная)"
      value_template: >
        {{ state_attr('sensor.temperature_158d0003230618', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d0003931aec:
      friendly_name: "Заряд батареи датчика температуры (Детская)"
      value_template: >
        {{ state_attr('sensor.temperature_158d0003931aec', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d0003931b0e:
      friendly_name: "Заряд батареи датчика температуры (Спальня)"
      value_template: >
        {{ state_attr('sensor.temperature_158d0003931b0e', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d00035ff631:
      friendly_name: "Заряд батареи кнопки (Кухня)"
      value_template: >
        {{ state_attr('binary_sensor.switch_158d00035ff631', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d0003045123:
      friendly_name: "Заряд батареи датчика движения (Кухня)"
      value_template: >
        {{ state_attr('binary_sensor.motion_sensor_158d0003045123', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d0003931a55:
      friendly_name: "Заряд батареи датчика температуры (Ванная)"
      value_template: >
        {{ state_attr('sensor.temperature_158d0003931a55', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d00039e2ecb:
      friendly_name: "Заряд батареи датчика температуры (Кладовая)"
      value_template: >
        {{ state_attr('sensor.temperature_158d00039e2ecb', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d000400e77d:
      friendly_name: "Заряд батареи датчика протечки (Кладовая)"
      value_template: >
        {{ state_attr('binary_sensor.water_leak_sensor_158d000400e77d', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d000309920a:
      friendly_name: "Заряд батареи датчика движения (Прихожая)"
      value_template: >
        {{ state_attr('binary_sensor.motion_sensor_158d000309920a', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d00044cea8e:
      friendly_name: "Заряд батареи датчика движения (Детская)"
      value_template: >
        {{ state_attr('binary_sensor.motion_sensor_158d00044cea8e', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d00031c790f:
      friendly_name: "Заряд батареи датчика входной двери"
      value_template: >
        {{ state_attr('binary_sensor.door_window_sensor_158d00031c790f', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d00039cf974:
      friendly_name: "Заряд батареи датчика кондиционера (Детская)"
      value_template: >
        {{ state_attr('binary_sensor.door_window_sensor_158d00039cf974', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d0004073b67:
      friendly_name: "Заряд батареи датчика кондиционера (Спальня)"
      value_template: >
        {{ state_attr('binary_sensor.door_window_sensor_158d0004073b67', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d0003d54725:
      friendly_name: "Заряд батареи датчика кондиционера (Гостиная)"
      value_template: >
        {{ state_attr('binary_sensor.door_window_sensor_158d0003d54725', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d0003fac0ec:
      friendly_name: "Заряд батареи датчика движения Aqara (Кухня)"
      value_template: >
        {{ state_attr('binary_sensor.motion_sensor_158d0003fac0ec', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"