#################################################
# AC binary sensors
#################################################

- platform: template
  sensors:
    ac_nursery_status:
      device_class: power
      value_template: "{{ is_state('binary_sensor.door_window_sensor_158d00039cf974', 'on') }}"
    ac_living_room_status:
      device_class: power
      value_template: "{{ is_state('binary_sensor.door_window_sensor_158d0003d54725', 'on') }}"
    ac_bedroom_status:
      device_class: power
      value_template: "{{ is_state('binary_sensor.door_window_sensor_158d0004073b67', 'on') }}"