#################################################
# Miscellaneous binary sensors
#################################################

- platform: workday
  country: RU
- platform: tod
  name: time_between_17_21
  after: '17:00'
  before: '21:00'
- platform: tod
  name: time_between_7_10
  after: '7:00'
  before: '10:00'
- platform: sauresha
  email: !secret saures_user
  password: !secret saures_pass
  flat_id: !secret saures_flat_id
  counters_sn:
    - 000-111