#################################################
# New Year's Holidays automatization
#################################################

- alias: 'New Year Light - Off [Home Presence]'
  hide_entity: false
  initial_state: true
  trigger:
    platform: state
    entity_id: group.family_persons
    to: "not_home"
    for:
      minutes: 5
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.plug_158d00033b702e
    - service: switch.turn_off
      data:
        entity_id: switch.tplink_smartplug_02
    - service: switch.turn_off
      data:
        entity_id: switch.tplink_smartplug_01
    - service: notify.telegram_stall
      data:
        message: Отключаем новогоднюю подсветку (никого нет дома).

- alias: 'New Year Light - On [Home Presence]'
  hide_entity: false
  initial_state: true
  trigger:
    platform: state
    entity_id: group.family_persons
    from: "not_home"
    to: "home"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.plug_158d00033b702e
    - service: switch.turn_on
      data:
        entity_id: switch.tplink_smartplug_02
    - service: switch.turn_on
      data:
        entity_id: switch.tplink_smartplug_01
    - service: notify.telegram_stall
      data:
        message: Включаем новогоднюю подсветку (кто-то пришел домой).

- alias: 'New Year Light - Off [Scheduled]'
  hide_entity: false
  initial_state: true
  trigger:
    - platform: time
      at: '23:30:00'
  condition:
    condition: template
    value_template: '{{ states("sensor.date")[-5:] != 12-31 }}'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.plug_158d00033b702e
    - service: switch.turn_off
      data:
        entity_id: switch.tplink_smartplug_02
    - service: switch.turn_off
      data:
        entity_id: switch.tplink_smartplug_01
    - service: notify.telegram_stall
      data:
        message: Отключаем новогоднюю подсветку (пора спать).

- alias: 'New Year Light - On [Scheduled]'
  hide_entity: false
  initial_state: false
  trigger:
    - platform: time
      at: '07:00:00'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.plug_158d00033b702e
    - service: switch.turn_on
      data:
        entity_id: switch.tplink_smartplug_02
    - service: switch.turn_on
      data:
        entity_id: switch.tplink_smartplug_01
    - service: notify.telegram_stall
      data:
        message: Включаем новогоднюю подсветку (с добрым утром).