#################################################
# Miscellaneous automatization
#################################################

- alias: 'Громкость радио'
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >
        {% if is_state("input_select.output_device", "Гостинная") %} media_player.gostinaia
        {% elif is_state("input_select.output_device", "Гостинная (Home Mini)") %} media_player.googlehome9967
        {% elif is_state("input_select.output_device", "Детская") %} media_player.detskaia
        {% endif %}
      volume_level: '{{  states.input_number.volume_radio.state  }}'
