#################################################
# Media automatization
#################################################

- alias: 'PowerOff all media when nobody at home'
  initial_state: true
  trigger:
    platform: state
    entity_id: group.family_persons
    to: "not_home"
    for:
      minutes: 5
  action:
    - service: media_player.turn_off
      data:
        entity_id: group.all_tv
    - service: switch.turn_off
      data:
        entity_id: switch.samsung_7_series_43
    - service: media_player.media_stop
      data:
        entity_id: group.all_chromecasts

- alias: 'Громкость радио'
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >
        {% if is_state("input_select.output_device", "Гостинная (TV)") %} media_player.gostinaia
        {% elif is_state("input_select.output_device", "Гостинная (Home Mini)") %} media_player.googlehome9967
        {% elif is_state("input_select.output_device", "Детская (TV)") %} media_player.detskaia
        {% elif is_state("input_select.output_device", "Детская (Home Mini)") %} media_player.googlehome3792
        {% endif %}
      volume_level: '{{  states.input_number.volume_radio.state  }}'