#################################################
# Lights Automations
#################################################

- alias: 'Kids must sleep at night'
  initial_state: true
  trigger:
    platform: state
    entity_id: light.detskaia
    to: 'on'
    for:
      minutes: 2
  condition:
    condition: time
    after: '0:00'
    before: '6:30'
  action:
    - service: homeassistant.turn_off
      entity_id: light.detskaia
    - service: notify.telegram_stall
      data:
        message: _{{ now().strftime("%d.%m.%Y %H:%M:%S") }}_ автоматически выключен свет в детской.

- alias: 'Подсветка на кухне (кнопка Xiaomi)'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00035ff631
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.kukhnia_lenta

- alias: 'Подсветка на кухне (сенсор движения - вкл)'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0003fac0ec
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '21:30'
        before: '7:30'
      - condition: numeric_state
        entity_id: sensor.illumination_158d0003fac0ec
        below: 15
  action:
    service: homeassistant.turn_on
    entity_id: light.kukhnia_lenta

- alias: 'Подсветка на кухне (сенсор движения - выкл)'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0003fac0ec
    to: 'off'
    for:
      minutes: 3
  condition:
    condition: time
    after: '21:30'
    before: '7:30'
  action:
    service: homeassistant.turn_off
    entity_id: light.kukhnia_lenta

- alias: 'Вкл-Выкл включения подсветки от сенсора движения'
  hide_entity: true
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00035ff631
      click_type: double
  action:
    service: homeassistant.toggle
    data:
      entity_id:
        - automation.podsvetka_na_kukhne_sensor_dvizheniia_vkl
#        - automation.podsvetka_na_kukhne_sensor_dvizheniia_vykl

- alias: 'Свет в кладовой (сенсор движения - вкл)'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0003045123
    to: 'on'
  condition:
    condition: state
    entity_id: light.sonoff_1000b6831b
    state: 'off'
  action:
    service: light.turn_on
    entity_id: light.sonoff_1000b6831b

- alias: 'Свет в Кладовой (сенсор движения - выкл)'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0003045123
    to: 'off'
#    for:
#      minutes: 3
  condition:
    condition: state
    entity_id: light.sonoff_1000b6831b
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.sonoff_1000b6831b

- alias: 'Свет в детсокй Вкл-Выкл'
  initial_state: true
  trigger: 
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00033efd9e
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.detskaia

- alias: 'Яркость света в детской'
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00033efd9e
      click_type: double
  action:
    service: light.turn_on
    data_template:
      entity_id: light.detskaia
      transition: '1'
      brightness: >
        {%- if state_attr('light.detskaia', 'brightness') <= 3 %}
          51
        {% elif state_attr('light.detskaia', 'brightness') <= 51 %}
          102
        {% elif state_attr('light.detskaia', 'brightness') <= 102 %}
          153
        {% elif state_attr('light.detskaia', 'brightness') <= 153 %}
          204
        {% elif state_attr('light.detskaia', 'brightness') <= 204 %}
          255
        {% elif state_attr('light.detskaia', 'brightness') <= 255 %}
          3
        {% endif %}
